#!/bin/bash

mkdir /etc/PackSystemdir 1>/dev/null 2>/dev/null
mkdir /etc/PackSystemdir/senha 1>/dev/null 2>/dev/null
if [ $(id -u) -eq 0 ]
then
	echo "\033[1;34mNome Do Usuario:\033[0;37m"; read -p " " name
	echo "\033[1;34mSenha Para o Usuario $name:\033[0;37m"; read -p " " pass
	echo "\033[1;34mValidade Do Usuario $name :\033[0;37m"; read -p " " daysrnf
	echo "\033[0m"
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "\033[1;31mUsuario $name Ja Existe\033[0m"
	else
		valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
		datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
		useradd -M -s /bin/false $name -e $valid
		(echo $pass; echo $pass)|passwd $name 2>/dev/null
		echo "\033[1;34mUsuario: \033[0m$name"
		echo "\033[1;34mSenha: \033[0m$pass"
		echo "\033[1;34mExpira:\033[0m $datexp"
	    echo "$pass" > /etc/PackSystemdir/senha/$name
	fi
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "Seu usuario esta no grupo sudo"
	echo "Para virar root execute \033[1;31msudo su\033[0m"
	echo "Ou execute o Usercreate como sudo. \033[1;31msudo Usercreate\033[0m"
	else
	echo "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	fi
fi
