#!/bin/bash

read -p "Qual o Nome do Usuario a Alterar: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer Não Existe"
 exit
 fi
clear
echo "\033[1;31mO Que Você Quer Alterar ?
\033[0;34m[1] Alterar Numeros De Logins
[2] Altera Data de Expiraçao
[3] Mudar Senha do Usuario"
read -p "opção: " option
if [ $option -eq 1 ]; then
read -p "Qual o Novo Limite de Logins: " liml
rm /etc/usuarios/$namer.sh
rm /etc/tempo/$namer.sh
limit $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Qual a Data Que Deseja Por: Formato AAAA/MM/DD"
read -p ": " date
chage -E $date $namer 2> /dev/null
echo "\033[1;31mUsuario $namer 
Data: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Qual a Nova Senha Para $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/PackSystemdir/senha/$namer
echo "Nova Senha Adicionada"
exit
fi
echo "Essa Opçao Não Existe\033[0m"
